### ISSUE TITLE
Discriminate event listeners on same object

### ISSUE THREAD

**Issue by ReallyRad** [DanielEverland/ScriptableObject-Architecture#155]
Hello, 
Bit of a workflow question here. I have a GameObject which responds to two different kinds of event types, however one of those game events must not trigger any action until the first one has been triggered. 

So I would like to disable one of the event listeners until I received some other event trigger. But both those events reside on the same GameObject. I cannot access the event type from script since the field is protected. Is there a way I can discriminate between those event listeners to enable/disable them separately?

Thanks.

**Comment by LongChau** [comment]
Hello, 
If you have 2 events in a same objects. Even if you make 2 event listener in inspector. They would work like you register them on Awake() or Start() callback of the MonoBehaviour. 
Let's say, you have 2 events: FirstEvent and SecondEvent.
I think you should use SecondEvent.AddListener(Handle_SecondEvent) inside your Handle_FirstEvent callback of the FirstEvent. In that way it makes sure you listen the second event and handle it after the first event is executed. 
Sorry for my bad pronunciation, but I hope you get the ideas...

**Comment by ReallyRad** [comment]
Thanks for the answer. But I think I didn't express myself properly. 

My issue is that in the Unity inspector, I have no way of assigning two different instances of a GameEventListener to another script on that same GameObject. Or do I?

What I get from the interface is that it doesn't make a difference although there is (they are two different scripts)
<img width="723" alt="Screenshot 2021-10-18 at 17 48 28" src="https://user-images.githubusercontent.com/996367/137765544-23bf3f1e-7795-4a42-836b-782615d3e7cb.png">

The only way I could think of doing that would be instantiating those components by script, so I know which one is which, but that defeats the purpose of using the inspector.

I hope I'm making sense.

**Comment by LongChau** [comment]
> What I get from the interface is that it doesn't make a difference although there is (they are two different scripts)

Actually they are different, because Unity detects the different by a instance id. So don't worry.
![image](https://user-images.githubusercontent.com/40262027/137824868-d495d9a2-a648-41f5-8ab3-adbae2358153.png)

How about disable one GameEventListener? And in the Response of the first one, you enable the second one? 
![image](https://user-images.githubusercontent.com/40262027/137825495-e2b0a981-3de2-4e46-b18d-f06d43ced62d.png)

In case you want to do it in script. In the Panel Dimmer you make _listener2.enabled = false. And turn it to "true" when you receive response of the _listener1.

That makes second event listener enable back again and start to listen.

**Comment by ReallyRad** [comment]
Thanks a lot! This should work. I will try.

**Comment by LongChau** [comment]
Nice. Tell me your result when you finish. Hope you success.

**Comment by ReallyRad** [comment]
This worked. Thanks for the tip.
