### ISSUE TITLE
Support RuntimeValue for variables

### ISSUE THREAD

**Issue by hadmaerd** [DanielEverland/ScriptableObject-Architecture#51]
Variables must have the possibility to NOT serialize their changes during playmode, otherwise you will have to reset them manually each time by hands or in some Start() functions

**Comment by DanielEverland** [comment]
Not going to implement this since that's not how Scriptable Objects work.

I recommend watching the video linked in the README to see how you should tackle this

**Comment by hadmaerd** [comment]
@DanielEverland ok then I will have to implement it myself using your code as the base, it's going to be easy. I will add some "not serialize in playmode" checkmark and do separate editor draw for variable in editor and play mode (to avoid manual changes of initial value by hands during playmode). Thank you for your reply anyway.

**Comment by hadmaerd** [comment]
@DanielEverland ye but I will be disconnected from future updates of this nicely done asset :(

**Comment by DanielEverland** [comment]
If you fork the repo you can stay up to date :)
https://help.github.com/articles/syncing-a-fork/

**Comment by hadmaerd** [comment]
@DanielEverland why do you think it's so wrong? It seems flexible to me.
![runtime_value](https://user-images.githubusercontent.com/6717257/52816990-96469c80-30b3-11e9-9e18-62dbc3cccb32.gif)

**Comment by DanielEverland** [comment]
It's not me making that call, you're quite simply using Scriptable Objects incorrectly. This goes against Unity's own convention.

**Comment by hadmaerd** [comment]
@DanielEverland ok I got your point, but mine is not that far. In build your SOs will be reseted between each game run, so I want to mimicri this behaviour in editor as well to save my time and make me able to not think about some variables, that I should not to forget reset after entering play mode. It also brings some consistency in behaviour in editor and build (playmode wise).

**Comment by DanielEverland** [comment]
And you're free to do that in your own repo. I'm not going to design directly against Unity's convention.

**Comment by hadmaerd** [comment]
@DanielEverland ok, last question, what if you leave init value in inspector anyway (to not break Unity's convention related to SO that hard), but add runtime value as feature/extension?
![6c039f8e8ad74c7361571f3cb111ffb9](https://user-images.githubusercontent.com/6717257/52818199-20dccb00-30b7-11e9-8903-7befa1636a7f.png)

**Comment by BartInTheField** [comment]
Hi, I have been wanting to implement such a feature as well and just wondered why it was against Unity's convention? In an article published on Unity's website they even discuss the possibility of runtime only changes.

**Comment by DanielEverland** [comment]
I say it's against convention since they're implemented to keep runtime changes. Unity documentation isn't always proper, so take it with a grain of salt. They recommend making fields public in order to expose them to the inspector, which is terrible practice, and not something they even do themselves from what I've read of the C# source.

Thankfully, implementing this feature is super easy. You can fork my repo and add it to your own, that way you would also still get future updates :)

**Comment by BartInTheField** [comment]
Thank you for your explanation! :)

**Comment by DanielEverland** [comment]
np :)

**Comment by GasparErrobidart** [comment]
Hey fantastic work, I just discovered the whole SO paradigm recently and I've faced this same question.
I've wrote an article sharing my ideas on how to handle it: https://gasparerr.medium.com/scriptableobjects-how-to-keep-original-values-8423422103cf

Basically I'm adding an option to the inspector for values so they won't get modified in runtime, instead of reseting before/after play and managing indexes and copying SO instances. It uses MonoBehaviour to  store values in runtime and reflect them.

I'm new to C# and game dev, so I'll appreciate any feedback.
