### ISSUE TITLE
Stacktrace and Debug visuals not displaying in Unity 2019.2.0f1

### ISSUE THREAD

**Issue by raz818** [DanielEverland/ScriptableObject-Architecture#84]
I tried raising the OnPlayerDamaged event in play mode and edit mode as well as through the "raise" button and actually triggering the event by running into the spheres. In all cases I did not see any output. I also am seeing no debug visuals. Checked all gizmos settings and they should be showing.

**Comment by DanielEverland** [comment]
Thanks for reporting this issue, I've unfortunately identified both as being Unity bugs introduced in 2019.2

The first issue is caused by 2019.2 not drawing anything called by EdiotorGUI within a EditorGUILayout.BeginFadeGroup() scope

The second issue is caused by OnDrawGizmos() not being called unless you interact with the Unity editor

I've forwarded both issues to Unity, hopefully they'll fix them in the coming release. There's nothing I can do about it on my end, though.
