### ISSUE TITLE
Cannot display value. No PropertyDrawer for {V}

### ISSUE THREAD

**Issue by grigb** [DanielEverland/ScriptableObject-Architecture#94]
I enjoyed being able to edit the values for SO in the editor. Now I can't. What is a property drawer, how do I use them, and why?

**Comment by DanielEverland** [comment]
If the type you're trying to inspect is one you've made yourself, you have to create a Property Drawer for it, since I can't just ask Unity to draw the one it uses in the inspector. Here's a guide on what Property Drawers are: https://docs.unity3d.com/2018.3/Documentation/ScriptReference/PropertyDrawer.html

I did recently change how SO-A detects Property Drawers, so it could be that you've stumbled onto a recently introduced bug. Did you install using the package manager? If so, that might be the most likely cause.

**Comment by Folorox** [comment]
Probably a regression. Happens to me on a freshly cloned repo even with `FloatVariable`s.
![Regression](https://user-images.githubusercontent.com/54927249/67377790-bd743880-f575-11e9-9e73-b6000ce3f729.png)

**Comment by DanielEverland** [comment]
Ahhh I think I know what's wrong, the new system is much better at detecting user-made property drawers, but I probably forgot to include Unity's. Should be an easy fix :)

**Comment by DanielEverland** [comment]
Fixed, thanks for the report :)
